[package]
name = "rbspy-testdata"
version = "0.1.7"
authors = ["Kamal Marhubi <kamal@marhubi.com>", "Adam Jensen <adam@acj.sh>"]
description = "Test data for rbspy"
license = "MIT"
repository = "https://github.com/rbspy/rbspy-testdata"
homepage = "https://github.com/rbspy/rbspy-testdata"
readme = "README.md"
edition = "2021"

[dependencies]
anyhow = "1.0"
elf = "0.0.12"
flate2 = "1.0.20"
libc = "0.2.15"
remoteprocess = "0.4.3"
