[package]
name = "rbspy-testdata"
version = "0.1.4"
authors = ["Kamal Marhubi <kamal@marhubi.com>", "Adam Jensen <adam@acj.sh>"]
description = "Test data for rbspy"
license = "MIT"
repository = "https://github.com/rbspy/rbspy-testdata"
homepage = "https://github.com/rbspy/rbspy-testdata"
readme = "README.md"


[dependencies]
byteorder = "1.4.3"
elf = "0.0.10"
failure = "0.1.1"
flate2 = "1.0.20"
libc = "0.2.15"
remoteprocess = "0.4.3"
