[package]
name = "rbspy-testdata"
version = "0.1.0"
authors = ["Kamal Marhubi <kamal@marhubi.com>"]

[dependencies]
byteorder = "0.5"
elf = "0.0.10"
failure = "0.1.1"
flate2 = "0.2.14"
lazy_static = "0.2.1"
libc = "0.2.15"
read-process-memory = "0.1.0"
